cmr_data_path: "C:/Users/carlf/Documents/GitHub/LawIntelAfrica/data/03_primary"
benin_data_path: "C:/Users/carlf/Documents/GitHub/LawIntelAfrica/data/01_raw/benin"

data_path: "C:/Users/carlf/Documents/GitHub/LawIntelAfrica/data/01_raw/cmr/pdfs"
folder_params: "C:/Users/carlf/Documents/GitHub/LawIntelAfrica/data/01_raw/cmr/texts"
model_name: "all-MiniLM-L6-v2"
embeddings_path: "C:/Users/carlf/Documents/GitHub/LawIntelAfrica/data/06_models/embeddings"


chunk_size: 1000

chroma_params_1:
  persist_directory: "data/chroma/category"
  collection_name: "rag_documents"

chroma_params_2:
  persist_directory: "data/chroma"
  collection_name: "rag_documents"
split_params_1: True 
split_params_2: False