data_paths: 
  cmr: "C:/Users/carlf/Documents/GitHub/AfricAI/data/01_raw/cmr/pdfs"
  ben: "C:/Users/carlf/Documents/GitHub/AfricAI/data/01_raw/ben/pdfs"

folder_params: 
  cmr: "C:/Users/carlf/Documents/GitHub/AfricAi/data/01_raw/cmr/texts"
  ben: "C:/Users/carlf/Documents/GitHub/AfricAi/data/01_raw/ben/texts"
model_name: "all-MiniLM-L6-v2"
embeddings_path: "C:/Users/carlf/Documents/GitHub/AfricAi/data/06_models/embeddings"

ben: ben
cmr: cmr

chunk_size: 1000

chroma_params_1:
  persist_directory: "data/chroma/category"
  collection_name: "rag_documents"

chroma_params_2:
  persist_directory: "data/chroma"
  collection_name: "rag_documents"
split_params_1: 
  path: ./vector_stores/split_per_category/
split_params_2:   
  path: ./vector_stores/filtered_by_year/
  years_to_keep:
    - 2025
    - 2024



expected_columns:
  - text 
  - page_label 
  - page_title 
  - URL 
  - metadata 
  - category
  - text_length